##
##  Visopsys
##  Copyright (C) 1998-2023 J. Andrew McLaughlin
##
##  Makefile
##

BUILDDIR = build
OUTPUTDIR = ../../../${BUILDDIR}/system/headers/arpa

all:
	mkdir -p ${OUTPUTDIR}
	cp *.h ${OUTPUTDIR}

clean:
	rm -f *~
	rm -Rf ${OUTPUTDIR}

